# parent job is defined in openstack-manuals
- job:
    name: build-tox-manuals-buildpdf
    parent: build-tox-manuals
    vars:
      tox_envlist: buildpdf


- project:
    templates:
      - check-requirements
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    check:
      jobs:
        - build-tox-manuals-buildpdf
        - openstack-tox-pep8
    gate:
      jobs:
        - build-tox-manuals-buildpdf
        - openstack-tox-pep8
    post:
      jobs:
        - publish-openstack-python-branch-tarball
